
export const bible_books_newbooks = [
    {value: "Matthew", label: "Matthew"},  
    { value:"Mark", label: "Mark"},
    { value:"Luke", label: "Luke"},
    { value:"John", label: "John"},
    { value:"Acts", label: "Acts"},
    { value:"Romans", label: "Romans"},
    { value:"1 Corinthians", label: "1 Corinthians"},
    { value:"2 Corinthians", label: "2 Corinthians"},
    { value:"Galatians", label: "Galatians"},
    { value:"Ephesians", label: "Ephesians"},
    { value:"Philippians", label: "Philippians"},
    { value:"Colossians", label: "Colossians"},
    { value:"1 Thessalonians", label: "1 Thessalonians"},
    { value:"2 Thessalonians", label: "2 Thessalonians"},
    { value:"1 Timothy", label: "1 Timothy"},
    { value:"2 Timothy", label: "2 Timothy"},
    { value:"Titus", label: "Titus"},
    { value:"Philemon", label: "Philemon"},
    { value:"Hebrews", label: "Hebrews"},
    { value:"James", label: "James"},
    { value:"2 Peter", label: "2 Peter"},
    { value:"1 John", label: "1 John"},
    { value:"2 John", label: "2 John"},
    { value:"3 John", label: "3 John"},
    { value:"Jude", label: "Jude"},
        { value: "Revelation", label: "Revelation" },
    ]