export const oldtestamentbooks = [
    {value :"GENESIS", label: "Genesis"},  
    {value :"EXODUS", label: "Exodus"},
    {value :"LEVITICUS", label: "Leviticus"},
    {value :"NUMBERS", label: "Numbers"},
    {value :"Deuteronomy", label: "Deuteronomy"},
    {value :"Joshua", label: "Joshua"},
    {value :"Judges", label: "Judges"},
    {value :"Ruth", label: "Ruth"},
    {value :"1 Samuel", label: "1 Samuel (1 Kings)"},
    {value :"2 Samuel", label: "2 Samuel (2 Kings)"},
    {value :"1 Kings", label: "1 Kings (3 Kings)"},
    {value :"2 Kings", label: "2 Kings (4 Kings)"},
    {value :"1 Chronicles", label: "1 Chronicles"},
    {value :"2 Chronicles", label: "2 Chronicles"},
    {value :"Ezra", label: "Ezra"},
    {value :"Nehemiah", label: "Nehemiah"},
    {value :"Esther", label: "Esther"},
    {value :"Job", label: "Job"},
    {value :"Psalms", label: "Psalms"},
    {value :"Proverbs", label: "Proverbs"},
    {value :"Ecclesiastes", label: "Ecclesiastes"},
    {value :"Song of Solomon", label: "Song of Solomon"},
    {value :"Isaiah", label: "Isaiah"},
    {value :"Jeremiah", label: "Jeremiah"},
    {value :"Lamentations", label: "Lamentations"},
    {value :"Ezekiel", label: "Ezekiel"},
    {value :"Daniel", label: "Daniel"},
    {value :"Hoseas", label: "Hoseas"},
    {value :"Joel", label: "Joel"},
    {value :"Amos", label: "Amos"},
    {value :"Obadiah", label: "Obadiah"},
    {value :"Jonah", label: "Jonah"},
    {value :"Micah", label: "Micah"},
    {value :"Nahum", label: "Nahum"},
    {value :"Habakkuk", label: "Habakkuk"},
    {value :"Zephaniah", label: "Zephaniah"},
    {value :"Haggai", label: "Haggai"},
    {value :"Zechariah", label: "Zechariah"},
    {value :"Malachi", label: "Malachi"},
]