export const libros_de_biblia =[
    { value:"MAT", label: "San Mateo"},
    { value:"MRK", label: "San Marcos"},
    { value:"LUK", label: "San Lucas"},
    { value:"JHN", label: "San Juan"},
    { value:"ACT", label: "Hechos"},
    { value:"ROM", label: "Romanos"},
    { value:"1CO", label: "1 Corintios"},
    { value:"2CO", label: "1 Corintios"},
    { value:"GAL", label: "Gálatas"},
    { value:"EPH", label: "Efesios"},
    { value:"PHP", label: "Filipenses"},
    { value:"COL", label: "Colonseses"},
    { value:"1TH", label: "1 Tesalonicenses"},
    { value:"2TH", label: "2 Tesalonicenses"},
    { value:"1TI", label: "1 Timoteo"},
    { value:"2TI", label: "2 Timoteo"},
    { value:"TIT", label: "Tito"},
    { value:"PHM", label: "Filemón"},
    { value:"HEB", label: "Hebreos"},
    { value:"JAS", label: "Santiago"},
    { value:"1PE", label: "1 Pedro"},
    { value:"2PE", label: "2 Pedro"},
    { value:"1JN", label: "1 Juan"},
    { value:"2JN", label: "2 Juan"},
    { value:"3JN", label: "3 Juan"},
    { value:"JUD", label: "Judas"},
    { value:"REV", label: "Apocalipsis"},
    ]