export const libros_de_biblia = [
   {value:"GEN", label:"Génesis"},
   {value:"EXO", label:"Éxodo"},
   {value:"LEV", label:"Levítico"},
   { value: "NUM", label: "Números" },
   { value: "DEU", label: "Deuteronomio" },
   { value: "JOS", label: "Josué" },
   { value: "JDG", label: "Jueces" },
   { value: "RUT", label: "Rut" },
   { value: "1SA", label: "1 Samuel" },
   { value: "2SA", label: "2 Samuel" },
   { value: "1KI", label: "1 Reyes" },
   { value: "2KI", label: "2 Reyes" },
   { value: "1CH", label: "1 Crónicas" },
   { value: "2CH", label: "2 Crónicas" },
   { value: "EZR", label: "Esdras" },
   { value: "NEH", label: "Nehemías" },
   { value: "EST", label: "Ester" },
   { value: "JOB", label: "Job" },
   { value: "PSA", label: "Salmos" },
   { value: "PRO", label: "Proverbios" },
   { value: "ECC", label: "Eclesiastés" },
   {value:"SNG", label: "Cantares"},
   {value:"ISA", label: "Isaías"},
   { value: "JER", label: "Jeremías"},
   {value:"LAM", label: "Lamentaciones"},
   {value:"EZK", label: "Ezequiel"},
   {value:"DAN", label: "Daniel"},
   {value:"HOS", label: "Oseas"},
   {value:"JOL", label: "Joel"},
   {value:"AMO", label: "Amós"},
   {value:"OBA", label: "Abdía"},
   {value:"JON", label: "Jonás"},
   { value: "MIC", label: "Miqueas" },
   {value:"NAM", label: "Nahúm"},
   {value:"HAB", label: "Habacuc"},
   {value:"ZEP", label: "Sofonias"},
   {value:"HAG", label: "Hageo"},
   {value:"ZEC", label: "Zacarías"},
   {value: "MAL", label: "Malaquias"},
] 